services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432" # HOST_PORT : CONTAINER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro # readonly

volumes:
  postgres_data:

# Author : rub3ck0r3
