services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env # i will use the same .env located here for the rest of the implementations => data integrity
    ports:
      - "5432:5432" # HOST_PORT : CONTAINER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro # readonly

  backend:
    build: ../src/backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000" # For now in development everything is set in local
    depends_on:
      - db # The rest of the implementations depend also on the database

volumes:
  postgres_data:

# Author : rub3ck0r3
